### ISSUE TITLE
[HELP] Is there an upgrade mechanism for upgrading to 1.1.0 ?

### ISSUE THREAD

**Issue by LightMoon** [Zer0CoolX/guacamole-install-rhel#101]
Hi,
I am currently on 1.0.0 version which I have it installed by your script.
wondering how I can upgrade to 1.1.0?
Should it be a clean install?

**Comment by justsomeusername2020** [comment]
You'll need to do a clean install. The install script only runs on a clean install, and a number of dependencies have changed anyway, such as free-rdp 2.0. Use a fresh install of CentOS 7.7, followed by a "sudo yum update" to update to newest packages, then finally run the latest install script.

**Comment by Zer0CoolX** [comment]
This question is answered in the Wiki:

https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/Warnings

> It is meant to be installed on a clean/fresh install of RHEL or CentOS. Trying the script on a server running other software, especially with any overlap of the software setup by the script will likely have negative results.

This script will always be for a fresh install, not upgrades. The biggest reason aside from added complexity...I simply cannot find clean, concise documentation on the proper way to do an in place upgrade.

Also, to date it has not been possible or recommended. 1.0.0 explicitly noted that the release broke compatibility with previous releases (0.9.14 being the immediately previous). While 1.1.0 says its compatible with 1.0.0 the notes specifically state:

> Regardless of inter-component compatibility, there are changes in 1.1.0 which may affect downstream packagers of guacamole-server and downstream users of libguac or the Guacamole protocol.

So many dependencies changed from 1.0.0 to 1.1.0 (freerdp2 for example) that I dont see an in place upgrade being feasible.

If I do find a safe upgrade path in the future, my plan would be to write an upgrade script separate from this script, do the proper testing and ensure it works as expected. It would be a big under taking.
