### ISSUE TITLE
[REQ] ability to run unattended via answer file

### ISSUE THREAD

**Issue by Marcus-James-Adams** [Zer0CoolX/guacamole-install-rhel#102]
This script is really useful in bringing everything needed into one package
It would enhance it if it was possible to specify an answer file so it could be run by CI/CD automation tooling.

**Comment by Zer0CoolX** [comment]
Thanks for the recommendation. I will heavily consider it, but expect if I do this it will be a long ways off.

A long ways back, initially I had it setup with the ability to use command line switches...but as the menus and options got more complex that became too much to keep up with.

As I see it I could approach this 2 ways:

1. Like above, add switches to the command line but figure I would face the same challenges as before. Complexity.
2. Simply code in the option to point to an answer file and have it extract from that answers to variables. Maybe less complicated but not simple.

My big concern is people then trying to use answer files before fully understanding the script and how Guacamole and everything else the script can do works.

As it is they at least need to read the menus and make selections with some info provided.

If you have any suggestions for making it easier to integrate this feature in let me know. Thanks

**Comment by Marcus-James-Adams** [comment]
That's exactly what I'm doing at the moment running it on an tempory image
to get the correct values that I need.

What if you had an option on the final save/apply menu to export  the
settings that could then be used as the input for a clean install?

**Comment by Zer0CoolX** [comment]
> What if you had an option on the final save/apply menu to export  the
settings that could then be used as the input for a clean install?

I sort of already planned to do this, see here: https://github.com/Zer0CoolX/guacamole-install-rhel/projects/2#card-24134634.

Also, another stance on this is I see a very limited benefit to implementing this. Maybe my perspective is wrong but this script is not intended for deploying a cluster of Guacamole servers and I see a very limited chance that someone has to deploy a large quantity of stand alone Guacamole servers in a short period.

As I am just one person doing this in my spare time I have to decide what to use my time on. Other features/efforts end up being more widely beneficial to implement, in my mind. For example; additional authentication methods like RADIUS, DUO, etc. or improving SSL security.

So, I am of course open to this and if time was no concern would likely have done it already. However, as things are this isn't a top priority for me and I already know implementing something like this would be a significant effort. I would have to add checks to try and limit answer file issues (checking what options are required, sometimes conditionally on other options selected), add logic to skip the menus and read from the answer file, work out a syntax that works but is easy for people to work with, etc.

I do appreciate the suggestion and will do my best, but like I said early if I do this, it will be a long way out. My number 1 priority right now is trying to come up with an updated script that works with RHEL/CentOS 8.x and its proving to be significantly different and challenging.
