### ISSUE TITLE
[BUG] Presence of subscription-manager not sufficient in identifying OS

### ISSUE THREAD

**Issue by Dragonpark** [Zer0CoolX/guacamole-install-rhel#103]
This script is misidentifying my CentOS server as RHEL due to the 'subscription-manager' package being present. This is insufficient to identifying the OS as this package is installed if the server is being managed by either Red Hat Satellite or Foreman. Would it not be better to identify OS using the contents of /etc/redhat-release instead? I am aware this can be changed, but a fresh OS install would be consistent. Additionally, since there is guided install as it is, the script could ask what the OS is if it is unable to identify it via /etc/redhat-release.

I changed the following line to fix it for me:
`if rpm -q subscription-manager 2>&1 > /dev/null; then OS_NAME="RHEL"; else OS_NAME="CentOS"; fi`
to this:
`if grep -q CentOS /etc/redhat-release; then OS_NAME="CentOS"; else OS_NAME="RHEL"; fi`

**Comment by Zer0CoolX** [comment]
Thank you for bringing this to my attention, I was unaware CentOS could have `subscription-manager` installed. At the time I figured it was a sure fire, easy way to be sure.

What are your thoughts on something like:

```if grep -q "CentOS" /etc/redhat-release; then
     OS_NAME="CentOS"
elif grep -q "Red Hat Enterprise" /etc/redhat-release; then
    OS_NAME="RHEL"
else
    echo "Unable to verify OS from /etc/redhat-release as CentOS or RHEL, this script is intended only for those distro's, exiting."
    exit 1
fi```

This would further the logic to exiting if it cannot confirm CentOS/RHEL with an error message.

If you do not see anything wrong with this, I can add it in. If you would like credit for it, submit a pull request and I can review it. Bonus points if you can test it (at least in your current setup) and confirm it works correctly.

I may not have time to immediately test the update but it seems minor enough that I feel safe to assume (to a degree) that it will work as long as you 2nd the opinion.

**Comment by Dragonpark** [comment]
Sorry for the delayed response. That looks good to me.

**Comment by Zer0CoolX** [comment]
I will put this change in a new branch called "testing-osid" for brief testing due to the other active issue at this time related to timezone.

Feel free to give it a shot and let me know if it works. Thanks

**Comment by Zer0CoolX** [comment]
Merged into master now. Closing this, Thanks for the help!
