### ISSUE TITLE
[HELP] Guacamole Duo 1.1.0 extension not working - Not sure if it is a bug

### ISSUE THREAD

**Issue by LightMoon** [Zer0CoolX/guacamole-install-rhel#104]
Hi guys!

I have difficulty in getting Duo 1.1.0 extension working with latest version Guacamole.

What I did.
Installed Guacamole 1.1.0 with the bellow script on a [newly installed and pathed Centos 7 as you advised](https://github.com/Zer0CoolX/guacamole-install-rhel/issues/101).

Did the following guide to enable 2FA for my Guacamole server.
https://guacamole.apache.org/doc/gug/duo-auth.html#installing-duo-auth

Unfortunately, I can not get in even after a successful authentication! the chrome browser stuck with this error. Requests to the server have been blocked by an extension.

I do appreciate if someone tries to reciprocate this error and tell me if this is bug or I have done something wrong.

**Details**
OS/Version: RHEL 7.6
Guacamole Source: Stable
Any other options selected from the script prompts: letsencrypt

**Error Message(s) and Logs (be sure not to include sensitive/personal information!)**
If an error occurred include the exact message from the display/log.

**Describe the Issue**
A clear and concise description of what the problem is.

the problem is not related to chrome extensions. I have tried on 3 different browsers, got the same result.

I enabled debug mode for Guacamole and here is the tail of var/log/messages.

As you can see the authentication was successful; however, I could not get it.

https://pastebin.com/hDjbGRft
```

org.apache.guacamole.auth.jdbc.base.EntityModel>,java.util.Collection<java.lang.String>)] - SqlSession not set for thread: 19, creating a new one
Feb 25 21:49:47 rdpgw server: 21:49:47.969 [http-bio-8080-exec-2] DEBUG o.a.i.t.jdbc.JdbcTransaction - Opening JDBC Connection
Feb 25 21:49:47 rdpgw server: 21:49:47.969 [http-bio-8080-exec-2] DEBUG o.a.i.d.pooled.PooledDataSource - Checked out connection 33420170 from pool.
Feb 25 21:49:47 rdpgw server: 21:49:47.969 [http-bio-8080-exec-2] DEBUG o.a.i.d.pooled.PooledDataSource - Testing connection 33420170 ...
Feb 25 21:49:47 rdpgw server: 21:49:47.985 [http-bio-8080-exec-2] DEBUG o.a.i.d.pooled.PooledDataSource - Connection 33420170 is GOOD!
Feb 25 21:49:47 rdpgw server: 21:49:47.985 [http-bio-8080-exec-2] DEBUG o.a.i.t.jdbc.JdbcTransaction - Setting autocommit to false on JDBC Connection [com.mysql.cj.jdbc.ConnectionImpl@1fdf38a]
Feb 25 21:49:47 rdpgw server: 21:49:47.988 [http-bio-8080-exec-2] DEBUG o.a.g.auth.mysql.MySQLEnvironment - Database recognized as MySQL 5.5.64.
Feb 25 21:49:48 rdpgw server: 21:49:48.034 [http-bio-8080-exec-2] DEBUG o.a.g.a.j.b.E.selectEffectiveGroupIdentifiers - ==>  Preparing: SELECT guacamole_entity.name FROM guacamole_user_group JOIN guacamole_entity ON guacamole_user_group.entity_id = guacamole_entity.entity_id JOIN guacamole_user_group_member ON guacamole_user_group.user_group_id = guacamole_user_group_member.user_group_id WHERE guacamole_user_group.disabled = false AND guacamole_user_group_member.member_entity_id = ?
Feb 25 21:49:48 rdpgw server: 21:49:48.035 [http-bio-8080-exec-2] DEBUG o.a.g.a.j.b.E.selectEffectiveGroupIdentifiers - ==> Parameters: 2(Integer)
Feb 25 21:49:48 rdpgw server: 21:49:48.037 [http-bio-8080-exec-2] DEBUG o.a.g.a.j.b.E.selectEffectiveGroupIdentifiers - <==      Total: 0
Feb 25 21:49:48 rdpgw server: 21:49:48.037 [http-bio-8080-exec-2] DEBUG o.m.g.t.TransactionalMethodInterceptor - [Intercepted method: public java.util.Set<java.lang.String> org.apache.guacamole.auth.jdbc.base.EntityService.retrieveEffectiveGroups(org.apache.guacamole.auth.jdbc.base.ModeledPermissions<? extends org.apache.guacamole.auth.jdbc.base.EntityModel>,java.util.Collection<java.lang.String>)] - SqlSession of thread: 19 committing
Feb 25 21:49:48 rdpgw server: 21:49:48.038 [http-bio-8080-exec-2] DEBUG o.m.g.t.TransactionalMethodInterceptor - [Intercepted method: public java.util.Set<java.lang.String> org.apache.guacamole.auth.jdbc.base.EntityService.retrieveEffectiveGroups(org.apache.guacamole.auth.jdbc.base.ModeledPermissions<? extends org.apache.guacamole.auth.jdbc.base.EntityModel>,java.util.Collection<java.lang.String>)] - SqlSession of thread: 19 terminated its life-cycle, closing it
Feb 25 21:49:48 rdpgw server: 21:49:48.038 [http-bio-8080-exec-2] DEBUG o.a.i.t.jdbc.JdbcTransaction - Resetting autocommit to true on JDBC Connection [com.mysql.cj.jdbc.ConnectionImpl@1fdf38a]
Feb 25 21:49:48 rdpgw server: 21:49:48.045 [http-bio-8080-exec-2] DEBUG o.a.i.t.jdbc.JdbcTransaction - Closing JDBC Connection [com.mysql.cj.jdbc.ConnectionImpl@1fdf38a]
Feb 25 21:49:48 rdpgw server: 21:49:48.045 [http-bio-8080-exec-2] DEBUG o.a.i.d.pooled.PooledDataSource - Testing connection 33420170 ...
Feb 25 21:49:48 rdpgw server: 21:49:48.046 [http-bio-8080-exec-2] DEBUG o.a.i.d.pooled.PooledDataSource - Connection 33420170 is GOOD!
Feb 25 21:49:48 rdpgw server: 21:49:48.046 [http-bio-8080-exec-2] DEBUG o.a.i.d.pooled.PooledDataSource - Returned connection 33420170 to pool.
Feb 25 21:49:48 rdpgw server: 21:49:48.047 [http-bio-8080-exec-2] INFO  o.a.g.r.auth.AuthenticationService - User "guacadmin" successfully authenticated from x.x.x.x.

```

**Comment by LightMoon** [comment]
![5jwi3tlffvi41](https://user-images.githubusercontent.com/1636991/75304138-b6986200-5896-11ea-964e-0d3d551792a0.png)

**Comment by Zer0CoolX** [comment]
I am sorry but I have not integrated DUO support into my script at this time. Its planned in my list of things to do but I have only written placeholder code for it.

I would recommend installing using my script and test without modifying anything first. If the install works you can try and enable DUO yourself, but I cannot support it. If you need support with DUO I suggest asking in the Guacamole forums.

I notice you made a issue related to an issue with DUO prior, maybe the same problem? :+1: https://github.com/Zer0CoolX/guacamole-install-rhel/issues/89

and

https://github.com/Zer0CoolX/guacamole-install-rhel/issues/87

**Comment by LightMoon** [comment]
I have done the recommendation part. Everything working perfectly if removes the DUO jar file.
Unfortunately, this time is not related to SELinux file labels, since I can see in the logs that DUO jar file has been successfully loaded.
I know this is not officially in the scope of your script. All I ask if you can confirm that the reason I am facing this issue is not related to the fact that I used your script to build my Guacamole gateway.

**Comment by Zer0CoolX** [comment]
> All I ask if you can confirm that the reason I am facing this issue is not related to the fact that I used your script to build my Guacamole gateway.

I honestly cannot do that 100% as I really do not know. My personal opinion is that its extremely unlikely. I assume from your prior posts you did have it working with my script at one point, so history would suggest that my script has not had an impact on if DUO will work or not. On the other hand I aim to make the results of the script as secure as possible. In doing so it is possible that I have locked something down that prevents DUO from working properly.

I think a likely issue is how much CentOS/RHEL 7.7 changed from previous versions and how packages have changed. Maybe a package that DUO relies on is no longer present, the right version, etc. This is just a hypothetical wild guess on my part.

As it sounds like the results work without DUO, the only thing I can say for sure is your issue would be best addressed in the Guacamole forum, reddit or some other place in which people can help more specifically related to DUO and post-Guac install.
