### ISSUE TITLE
[HELP] LDAP is not sync some users.

### ISSUE THREAD

**Issue by thiagocpv** [Zer0CoolX/guacamole-install-rhel#109]
Hi there!

I have installed the guacamole from stable version using your script with ldap authentication.
Everything is fine and working but some users from my AD/ldap is not synchronized.

BTW I can see all users using ldapsearch command.

I am using CentOS7 and I can't see so far any errors in the logs.

I am using the configuration bellow with ldap:

# LDAP properties
ldap-hostname: AD hostname
ldap-port: 389
ldap-user-base-dn: dc=company,dc=com,dc=br
ldap-search-bind-dn: CN=administrator,CN=Users,dc=company,dc=com,dc=br
ldap-search-bind-password: mypassword
ldap-username-attribute: sAMAccountName
ldap-user-search-filter: (objectClass=*)

Thank you very much.
Thiago

**Comment by Zer0CoolX** [comment]
My apologies for not responding more quickly, the world went nuts as I am sure everyone is aware of.

I am afraid I cannot offer help regarding this matter as it is specific to your AD/LDAP environment and not a result of the script.

I suggest you read the wiki page I wrote on LDAP [here](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/LDAP-or-LDAPS-Authentication) and the official documentation [here](https://guacamole.apache.org/doc/gug/ldap-auth.html). Especially the part about "ldap-user-base-dn"

> The base of the DN for all Guacamole users. This property is absolutely required in all cases. All Guacamole users **must be descendents of this base DN**.

There are countless ways a user or organization could structure AD/LDAP. The LDAP extension (and my script) simply interact with it given the parameters provided within the confines of how the extension works.

If you feel the extension is not working as it should, I recommend posting in the official Guacamole forum for help resolving the issue.

Good luck. If there is no response back in a few days I will close the issue. You can always re-open it if needed.

**Comment by thiagocpv** [comment]
Hi there!

No problem, I will try some thinks, maybe I can fix and back here to post the solution.
Thank you very much.

Thiago
