### ISSUE TITLE
[REQ] non-selinux script

### ISSUE THREAD

**Issue by ethaniel86** [Zer0CoolX/guacamole-install-rhel#111]
Thanks for this excellent script! Any chance i can run this on selinux-disabled VM?

**Comment by Zer0CoolX** [comment]
> ...Any chance i can run this on selinux-disabled VM?

**The short answer is**
- As is, no. I do not plan to provide options to make the script work without SEL enabled.
- If you modify the script yourself, yes. You can comment out the SEL related lines if you chose to do so and run the script without SEL. Keep in mind I cannot/will not help with modifying the script or with resolving issues that come about from having used a modified script.

**Longer answer**
First some points:

1. This script is meant to be installed on a clean install of RHEL/CentOS 7.7 (or >). Either a minimal install or a server with GUI install (likely true for other installs but not tested or recommended) enable SEL by default.
2. A big focus of my script is security. SEL is an important part of the overall security.
3. The script ensures that all aspects of what the script provides function properly with SEL enabled. The initial check for SEL being enabled in the script ensures 2 things: A. SEL is active to provide the layer of protection and B. that its enabled to prevent errors caused when the script attempts to configure SEL.

**With the above in mind...**

The only way SEL could be disabled is if a user disables it prior to running the script. As per 3 above, the only reason to do this would have nothing to do with the script/Guacamole. IE: Its likely in an effort to setup software not installed or configured by the script and likely not even related to Guacamole which is not supported or recommended by me.

2 speaks for itself along with 3, there is no reasonable situation to disable SEL to use the script to properly setup a Guacamole server as intended. Doing so will only lower the security of the system.

**Alternate Thoughts...**
It is possible that when using a container, IE: NOT a VM, that the host kernel does not support SEL. For example when running a CentOS/RHEL container in Proxmox (which is based on Debian and doesn't support SEL itself). I could see in such a situation having a valid reason to want to run the script without requiring or configuring SEL...

However, such a configuration is not (yet...who knows maybe in the future I will plan for this) supported by me. The intention has always been a bare metal or VM based OS install which then ensures SEL being present and enforced by default.

I hope this provides insight into the choice to require, check for and configure SEL via the script. Thanks

**Comment by ethaniel86** [comment]
Yes, thanks for the details! I will adjust the script accordingly.

**Comment by ServerMonkey** [comment]
I find myself in the situation needing to install Guacamole in LXC.
LXC does not support SELinux.
It would be really cool to have a flag to install without SELinux.
