### ISSUE TITLE
unable to finish installation

### ISSUE THREAD

**Issue by nimrodsab** [Zer0CoolX/guacamole-install-rhel#114]
Hi, first, thank you for the script, it is really a lifesaver.
Second, after completing the setup configuration, the script fails during the installation, with an error message saying "ERROR (Script Failed) | Line 1045 | Command: yum install -y .....l | Exit code: 1"
what could be the problem?

I appreciate your help.

**Comment by Zer0CoolX** [comment]
Please fill out a template and follow the directions in: https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/How-to-Report-Issues-(Bugs,-Feature-Request-and-Help)

Without the information requested its very difficult for me to answer your question. I cannot assume what version of the script you used, or what line 1045 is for you. You didnt even provide the full error message (I cant think of a reason why "yum install -y..." would appear, I am sure there is more to it).

I am closing this issue, if you still need help open a new issue, use the proper template and answer all the questions in the template, following the guide I linked to here for requesting help.
