### ISSUE TITLE
[HELP] SELinux permissive required for OpenID extension

### ISSUE THREAD

**Issue by gilleta** [Zer0CoolX/guacamole-install-rhel#117]
**Confirmation of Process**
1. You have read the [How to report issues](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/How-to-Report-Issues-(Bugs,-Feature-Request-and-Help)) wiki page? Y
2. You have read the wiki and followed its guidelines including requirements, troubleshooting, etc.? Y

**Details**
OS/Version: cent os 7.7
Guacamole Source: Stable

**Describe the bug**
OpenID authentication does not work when SELinux is enabled.

**Error Message(s) and Logs (be sure not to include sensitive/personal information!)**
If an error occurred include the exact message from the display/log.
var/log message relevant line:
_SELinux is preventing localhost-start from getattr access on the file /var/lib/guacamole/extensions/guacamole-auth-0openid-1.1.0.jar.

**To Reproduce**
Steps to reproduce the behavior (example):
1. Go to GUACAMOLE_HOME/extensions/
2. Add guacamole-auth-0openid-1.1.0.jar
3. Configure it properly
4. Restart tomcat service
5. OpenID jar is not detected by tomcat and you will stay with your default login.
6. Check journal and var/log messages. 

**Have You Found a Solution to the Issue?**
The easy workaround is to set SELinux to permissive : set "SELINUX=permissive" in /etc/selinux/config and reboot. Not sure this is the best move though.
The only thing I would do for now is to add a quick line in the doc to mention that (i only tested openid extension).

**Comment by Zer0CoolX** [comment]
To start, my script does not yet support OpenID. As such anything you are trying to do with OpenID and this script is on you.

Having said that, it sounds like you just need to set the proper SEL context for the OpenID extension. Also make sure the extension has the proper file permissions to operate.

The best way to do so is to set SEL to permissive, use the extension, check the sealerts/setroubleshoot messages and apply the recommended fixes they provide. Here is a link that may help you get started: https://www.serverlab.ca/tutorials/linux/administration-linux/troubleshooting-selinux-centos-red-hat/

I would not recommend disabling SEL long term. Its a security mechanism providing protections. Disabling it may get you past an issue, but it could cause gaps in your security.

Good luck

**Comment by gilleta** [comment]
Hi, as I said in the "Have You Found a Solution to the Issue?" I am well aware of all this and my setup is working.
I was just suggesting that you add a few lines to guid users that would want to use OpenID after installing guacamole with your script, not suggesting some devs to make the script compatible with OpenID (which neither you or me want to do apparently ;) )
So a word to the wise :)
