### ISSUE TITLE
[REQ] RADIUS Authentication

### ISSUE THREAD

**Issue by nimrodsab** [Zer0CoolX/guacamole-install-rhel#118]
Hi, Is it possible to add the Radius authentication as the Primary authentication method?
This will be a great tool and will offer a connection to the Azure MFA Server.

Thank you

**Comment by Zer0CoolX** [comment]
Hello,

I appreciate your feedback.

From a technical standpoint RADIUS as a primary authentication is possible. That is to say there is an extension for RADIUS and given the proper setup it would work.

From the standpoint of my script, it is currently not an option. While I have been hoping to add additional features like RADIUS to the script, doing so is a fairly large undertaking. I need to setup the infrastructure like a RADIUS server, figure out the code in the script for it to work, then test and troubleshoot the script until I am confident it is stable. This can be a time consuming process.

With the release of RHEL/CentOS 8.x, my focus has been on re-writing a script that works on RHEL/CentOS 8.x. I have, especially lately, limited time to work on this. As such, I need to pick and choose what I spend that limited time on.

So right now, my focus is on updating and creating a script that works with RHEL/CentOS 8.x. Once I have that worked out, then I hope to add features to it. For now, this 7.x script is essentially feature frozen. I update it so it keeps working and try and fix bugs but have no plans to add features to this script.

Once I have a version that works on RHEL/CentOS 8.x I will be focusing on that and this script will become less and less relevant as RHEL/CentOS 7.x get older, less widely used, etc.

So, you could likely get RADIUS to work after running this script but it would be a manual process and something I cant help with. By the time I do get around to adding RADIUS as an option, it will likely be a version of this script meant for RHEL/CentOS 8.x and likely be its own repository/project in my Github.
