### ISSUE TITLE
[BUG] If install has previously failed a new install attempt will fail due to created folders

### ISSUE THREAD

**Issue by anakaine** [Zer0CoolX/guacamole-install-rhel#120]
If a previous install has failed for whatever reason then new installs will continue to fail because when they attempt to create a folder the folder already exists. 

CentOS 7

**Comment by Zer0CoolX** [comment]
That is correct and not a bug. It is stated in at least one place that this is the case.

From the readme:
> No prior Guacamole installation or configuration including for its major dependent packages like Nginx, Tomcat, mariaDB, etc. **IE: if the script fails, you cannot simply re-run it!**
