### ISSUE TITLE
[BUG] Script Fails When Firewalld is Not Installed

### ISSUE THREAD

**Issue by anakaine** [Zer0CoolX/guacamole-install-rhel#121]
CentOS 7 - firewall-cmd not found

Looks like this is known on the images CentOS publish to the AWS marketplace. It might be worth checking if firewalld is installed first. 

Firewall Configuration
-firewalld is installed and started on the system... [-done-]
-Backing up firewall public zone to: /home/centos/guacamole-1.1.0_23-20-Apr.firewall.bkp [-done-]
-Opening HTTP and HTTPS service ports... [-FAILED-]

%%% ERROR (Script Failed) | Line 1721 | Command: firewall-cmd --permanent --zone=public --add-service=http | Exit code: 127 %%%

[centos@ip-172-31-0-233 ~]$  firewall-cmd --permanent --zone=public --add-service=http
-bash: firewall-cmd: command not found

**Comment by Zer0CoolX** [comment]
I see. The default/vanilla CentOS ISO/minimal install includes firewalld so I actually took the check for it out some time back.

As I am not familiar with AWS and its images, is it possible to install firewalld (what provides firewall-cmd) after setting the image up? (prior to running the script).

If so I can add the check back and have it install firewalld before continuing. If not, I can still add the check so the script doesn't run when firewalld is missing but it would be up to the user to decide to proceed without firewalld and manually comment out all the firewall related code in the script.

As my script prioritizes security I do not want to add code/options to it that encourage skipping over security measures.

It may be a few days before I get around to adding a check to it. Thanks

**Comment by Zer0CoolX** [comment]
Latest commit should resolve this by adding a check for firewalld at the start of the script. If not installed, the script will exit with a message. This script may be able to be run without firewalld by modifying the script but I cannot help with that.

I am going to close the issue, if the check does not work let me know by re-opening the issue or starting a new one. Keep in mind that it is my intention for firewalld to be a requirement. I will not change the script to not require it nor may I help with circumventing the requirement.
