### ISSUE TITLE
[HELP] guacd[2071]: Unable to create directory "path": Permission denied

### ISSUE THREAD

**Issue by hiroshclan** [Zer0CoolX/guacamole-install-rhel#126]
**Confirmation of Process**
1. You have read the [How to report issues](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/How-to-Report-Issues-(Bugs,-Feature-Request-and-Help)) wiki page? Yes
2. You read the [wiki](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki), checking all pages for information that may help you? Yes
3. You read other requests to ensure this question has not already been asked and/or resolved? Yes

**Details**
OS/Version: RHEL 7.8
Guacamole Source: Stable
Any other options selected from the script prompts:

**Error Message(s) and Logs (be sure not to include sensitive/personal information!)**
May  4 07:48:38 simda guacd[1048]: Creating new client for protocol "rdp"
May  4 07:48:38 simda guacd: guacd[1048]: INFO:#011Creating new client for protocol "rdp"
May  4 07:48:38 simda guacd[1048]: Connection ID is "$27213644-42ae-44dc-84b5-0114c8fe47ff"
May  4 07:48:38 simda guacd: guacd[1048]: INFO:#011Connection ID is "$27213644-42ae-44dc-84b5-0114c8fe47ff"
May  4 07:48:38 simda guacd[2071]: Security mode: RDP
May  4 07:48:38 simda guacd: guacd[2071]: INFO:#011Security mode: RDP
May  4 07:48:38 simda guacd: guacd[2071]: INFO:#011Resize method: display-update
May  4 07:48:38 simda guacd: guacd[2071]: INFO:#011User "@25070d89-9a21-4a6c-bd4f-b883afeaa92b" joined connection "$27213644-42ae-44dc-84b5-0114c8fe47ff" (1 users now present)
May  4 07:48:38 simda guacd: guacd[2071]: ERROR:#011Unable to create directory "/root/simpan": Permission denied
May  4 07:48:38 simda guacd[2071]: Resize method: display-update
May  4 07:48:38 simda server: 07:48:38.212 [http-bio-8080-exec-10] INFO  o.a.g.tunnel.TunnelRequestService - User "diskominfo" connected to connection "1".
May  4 07:48:38 simda server: 07:48:38.213 [http-bio-8080-exec-10] INFO  o.a.g.t.h.RestrictedGuacamoleHTTPTunnelServlet - Using HTTP tunnel (not WebSocket). Performance may be sub-optimal.
May  4 07:48:38 simda guacd[2071]: User "@25070d89-9a21-4a6c-bd4f-b883afeaa92b" joined connection "$27213644-42ae-44dc-84b5-0114c8fe47ff" (1 users now present)
May  4 07:48:38 simda guacd[2071]: Unable to create directory "/root/simpan": Permission denied
May  4 07:48:38 simda guacd: guacd[2071]: INFO:#011Loading keymap "base"
May  4 07:48:38 simda guacd: guacd[2071]: INFO:#011Loading keymap "en-us-qwerty"
May  4 07:48:38 simda guacd[2071]: Loading keymap "base"
May  4 07:48:38 simda guacd[2071]: Loading keymap "en-us-qwerty"
May  4 07:48:38 simda guacd[2071]: Connected to RDPDR 1.13 as client 0x0004
May  4 07:48:38 simda guacd: guacd[2071]: INFO:#011Connected to RDPDR 1.13 as client 0x0004
May  4 07:48:38 simda guacd[2071]: RDPDR user logged on
May  4 07:48:38 simda guacd: guacd[2071]: INFO:#011RDPDR user logged on
May  4 07:48:38 simda guacd[2071]: Unable to read file "/"
May  4 07:48:38 simda guacd: guacd[2071]: INFO:#011Unable to read file "/"
May  4 07:48:39 simda guacd[2071]: File open refused (-6): ""
May  4 07:48:39 simda guacd: guacd[2071]: ERROR:#011File open refused (-6): ""
May  4 07:49:40 simda guacd[2071]: RDP server closed connection: Manually logged off.
May  4 07:49:40 simda guacd: guacd[2071]: INFO:#011RDP server closed connection: Manually logged off.
May  4 07:49:40 simda guacd[2071]: Internal RDP client disconnected
May  4 07:49:40 simda guacd: guacd[2071]: INFO:#011Internal RDP client disconnected
May  4 07:49:40 simda guacd[2071]: User "@25070d89-9a21-4a6c-bd4f-b883afeaa92b" disconnected (0 users remain)
May  4 07:49:40 simda guacd: guacd[2071]: INFO:#011User "@25070d89-9a21-4a6c-bd4f-b883afeaa92b" disconnected (0 users remain)
May  4 07:49:40 simda guacd: guacd[2071]: INFO:#011Last user of connection "$27213644-42ae-44dc-84b5-0114c8fe47ff" disconnected
May  4 07:49:40 simda guacd[2071]: Last user of connection "$27213644-42ae-44dc-84b5-0114c8fe47ff" disconnected
May  4 07:49:40 simda guacd: guacd[1048]: INFO:#011Connection "$27213644-42ae-44dc-84b5-0114c8fe47ff" removed.
May  4 07:49:40 simda guacd[1048]: Connection "$27213644-42ae-44dc-84b5-0114c8fe47ff" removed.
May  4 07:49:41 simda server: 07:49:41.237 [http-bio-8080-exec-2] INFO  o.a.g.tunnel.TunnelRequestService - User "diskominfo" disconnected from connection "1". Duration: 63024 milliseconds
May  4 07:49:41 simda server: 07:49:41.247 [http-bio-8080-exec-5] INFO  o.a.g.tunnel.TunnelRequestService - User "diskominfo" disconnected from connection "1". Duration: 63033 milliseconds

**Describe the Issue**
Drive redirection error, and not functioning, 

**Additional context**
i already change permission of the folder as fully writeble

**Comment by Zer0CoolX** [comment]
Hello thanks for sharing the issue. Few things I want to confirm.

1. The script ran to completion? The script generated log file shows no errors?
2. Have you rebooted the system since running the script?
3. Does RDP work without the drive re-direction?
4. What settings have you used in the connection using RDP? IE: are you entering the user/password in the connection settings or when trying to connect, authentication type, ignore server cert, etc?
5. Where is the drive located that you are trying to redirect? Is it from a 3rd machine (not the guac host or RDP client)? If so, how is that machine/drive setup. Does that drive require credentials to use (like a samba share)?

I would also recommend doing a search online for the errors your getting (especially the permissions denied lines in the above log). Sometimes these kind of problems are known Guac or dependant package bugs, not an issue with the script.

If you provide detailed enough info I can try and replicate your setup and test it to see if I get the same issue and then try and trace it.

**Comment by Zer0CoolX** [comment]
Closed inactivity
