### ISSUE TITLE
Nginx server_name property for Self-signed vs LetsEncrypt

### ISSUE THREAD

**Issue by Zer0CoolX** [Zer0CoolX/guacamole-install-rhel#17]
I need to work out a variable and/or some logic to handle the server_name property when the cert is self signed vs when using LetsEncrypt. If using the current GUACSERVER_HOSTNAME variable, self-signed works (as this is generally localhost...not tested with a public domain) but LetsEncrypt would fail. Likewise, using DOMAIN_NAME sets up LetsEncrypt properly but fails for a self-signed cert.

Need to work out handling this, which may coincide with re-working the whole interactive menu for clarity.

**Comment by Zer0CoolX** [comment]
The issue isnt key length, its what to place in the `guacamole.conf` and `guacamole_ssl.conf` for the `server_name` property.

When only accessing the site from the LAN, something like `localhost` works just fine. However when using a public facing domain then it needs to be the public domain, like "mydomain.com".

So I have to re-work how I prompt for that information and under what context. Its basically just cleanup from the base code and new code put in.

This post issue was more a reminder for me to work on it than needing help, however I am happy to review any code that may solve the issue. Thanks however for your reply.

**Comment by berndhose** [comment]
For reaching the server via a public facing host-/domain-name a proper Internet based DNS entry is needed, Nginx supports virtual servers with a request's header field “Host” to determine which virtual server the request should be routed to,. More than one virtual server can reside on a host. Assuming that guacamole will run on its own host and no other virtual servers are present, any host-name will work, even an empty string "" is ok. I have tested various scenarios with success.

**Comment by Zer0CoolX** [comment]
This matter should be resolved by the merge found here https://github.com/Zer0CoolX/guacamole-install-rhel/pull/18
