### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by roelleke1985** [Zer0CoolX/guacamole-install-rhel#21]
**Confirmation of Process**
1. You have read the wiki and followed its guidlines, especially the [Installation Assunmptions](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/Installation-Assumptions) page? Y/N
2. You have checked the wiki and exisitng issues for the same problem? Y/N
3. You are sure this issue is not specific to you personally and would affect others under similar circumstances? Y/N

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs & Error Messages (be sure not to include sensitive/personal ifnormation!)**
May include various logs like the one generated by the script or another source like /var/log/messages. Error message could be while running the script or when attempting to use Guacamole.

**Screenshots (be sure not to include sensitive/personal information!)**

**Environment (please complete the following information):**
 - OS: [e.g. CentOS 7.6, RHEL 7.5, etc.]
 - OS Details: Installation method, Desktop Environment, etc. [e.g. minimal install, Server with GUI, Gnome, etc.]
 - Browser: Browser used from another machine other than the server to access Guacamole [e.g. chrome, safari]

**Guacamole Options Selected**
 - Extensions: [e.g. LDAP, custo, etc.]
 - Nginx: [e.g. security level, DHE, URI, etc.]
 - LetsEncrypt/Self-signed cert?
 - Circumstantial Settings: [e.g. LDAP info, LDAPS info, Key strengths, etc.]

**Have You Found a Solution to the Issue?**
Either by manually doing something before/after the script has run or by editing the script prior to running.

-------------------------------------------------------------------------------------------------------------------------
Goodmorning , 
Yesterday you helped me to get the script working and later on you updated the script to a new version but on the new version this question is missing

**Enter a valid domain for let's encrypt certificate (ex. gucamole.company.com):**

When the script is finished the server will not be able to connect to https .

When i use the older script everything is working out of the box.

I hope you understand me my english is not so good.
Thanks in advance

**Comment by roelleke1985** [comment]
this is the old working script .

![guacamoles_oldscript1](https://user-images.githubusercontent.com/46712588/51233027-02c16500-1969-11e9-894f-19f2a383d2ce.png)

this is the new script not working .

![guacamole_newscript](https://user-images.githubusercontent.com/46712588/51233052-1a005280-1969-11e9-9a2d-034d838e0832.png)

**Comment by Zer0CoolX** [comment]
Next time please fill out the form (the proper one, your asking for help, not to fix something that does not work the way it should). You didnt even bother putting a title in. If the solution to this was not as simple as I think it is I would have told you to resubmit the request.

We moved the prompt. you can still put in the public domain.

![image](https://user-images.githubusercontent.com/36512355/51258336-bb8ea080-1977-11e9-9d38-f1b7462ea6f4.png)

Using a public domain is not dependent on if you use LetsEncrypt or not. You could have a public domain with a self-signed cert or even without a cert at all.

I am going to close this request. If this does not solve your problem, open another using the proper request type, fill it out in its entirety and we will get it worked out. Its important you fill out the form as it gives me and others the information we need to most quickly help you resolve your problem. When people do not fill it out they are wasting their own time and others by putting those helping in a position in which they need to request the information that should have been included in the original request.

Thanks
