### ISSUE TITLE
IPv4/IPv6 are not properly set in nginx

### ISSUE THREAD

**Issue by dawid-woitaschek** [Zer0CoolX/guacamole-install-rhel#29]
The whole scripts fails after the startup of nginx is not successful:

`Feb 09 11:07:25 hostname systemd[1]: Starting nginx - high performance web server...
Feb 09 11:07:25 hostname nginx[24619]: nginx: [emerg] invalid port in upstream "111.222.333.44410.10.10.109z13:r4c5:6:d4::a47:9001:8080/guacamole/" in /etc/ngin...mole.conf:8
Feb 09 11:07:25 hostname systemd[1]: nginx.service: control process exited, code=exited status=1
Feb 09 11:07:25 hostname systemd[1]: Failed to start nginx - high performance web server.`

Please see the IP addresses... "111.222.333.444" would be my external IPv4, "10.10.10.10" would be my internal IPv4 and "9z13:r4c5:6:d4::a47:9001" would be my external IPv6 (in this case randomized ofc). There is no spacing at all.

This is the case in the SSL conf, too.

And another hint:
I've read, that "listen 80;" resp. "listen 443;" is obsolete and can cause a startup fail to, because of the port bindings. It should be enough to use "listen [::]:80;", which is using both IPv4 and IPv6.

**Comment by Zer0CoolX** [comment]
Please use the bug report issue template and fill it out as completely as you can to allow me to best help you. I will close this issue, please open a new one using the template.
