### ISSUE TITLE
[Notice] Feature Freeze

### ISSUE THREAD

**Issue by Zer0CoolX** [Zer0CoolX/guacamole-install-rhel#32]
I will not be adding any new features until further notice. (starting 2/13/2019)

The focus for now will remain on bug fixes, code cleanup and documentation revision.

With bug fixes being a priority, I intend to do further testing using a variety of different options to try and find and resolve bugs.

I also hope to cleanup the code both from a development and user perspective. This means writing code more efficiently, cutting out some of the "fat" and improving the structure and consistency of how the code is written making it easier for other developers to understand and use. From a user perspective, it means making menus, prompts, output and logging clear, precise and accurate.

Lastly, with the documentation revised for the recent big changes to the script I want to review and revise the documentation to proof read for spelling/grammar and to help re-word documentation for clarity.

Once these tasks are sufficiently complete, I will close this issue and proceed with implementing new features like additional Guacamole extensions. Thanks

**Comment by aekash** [comment]
Hi Zer0CoolX

Great piece of work!

Just wondering if you still plan on adding new features such as additional Guacamole extensions ?

Thanks
Aekash

**Comment by Zer0CoolX** [comment]
Yes. I have, a while back, added the foundation to add in other extensions. I have more recently put in a lot of effort to cleanup the code, bug fix and document it.

Some examples of more recent adjustments include:
- Added Error handling
- Added Content Security Policy (CSP)
- Completely revised logging in the entire script
- Fixed a bug caused by a newer release of Nginx
- Revised Nginx ssl configuration to remove weak ciphers and tweak parameters
- etc.

All of the above and more took extensive testing to ensure that the script worked as expected. Adding additional extensions will require me to learn how it works, be able to setup the infrastructure for those authentication methods and to be able to test and verify them. I expect that these additional extensions being added will be a long way off, months at least. I am also keeping an eye on how RHEL 8/CentOS 8 mature and once everything needed for Guacamole is available on the newer versions I will likely need to revise the script to work properly with them.

**Comment by aekash** [comment]
Thanks for the update :)

Some feedback (I'm probably doing it totally incorrectly)

I tried to use the "Custom Extension Menu" to try and install 2FA Google Authenticator Support TOTP

1. ) I supplied the The file name of the extension
2. ) I supplied the full path of the dir containing the .jar extension

The script got past installing the custom extenstion bit but when the "systemctl restart nginx" command was exectuted (happens towards the end of the script) the script fails with 

"Unregistered Authtentication Agent for unix-process:25592:1"

If I don't use the "Custom Extenstion" option, all works fine. Like I say it's probably me not doing something correct but just confused as why adding an extenstion would break things :(

Look forward to your updates to the script..

**Comment by Zer0CoolX** [comment]
The custom extension option is meant for user created extensions like the one I link to in the readme for customizing the login screen. Any of the official extensions for authentication will not work using this method without a lot of manual effort, basically no different then installing and configuring the additional extension manually. In other words it will not work for the official extensions.

What I meant earlier about laying the foundation for the additional official authentication extensions is that I have added some code into the script (some of which is commented out and not active) that will allow me to easily add them to; the prompts, summary menu and in other tasks which apply to all extensions, like setting SEL for them. You can see examples of this throughout the script (even if you do not understand Bash scripting or programming), for example: lines 481-490 (TOTP Menu) as its nothing more than a header and echo that its not ready. Compare that to the working LDAP menu (this is just the user input portion/menu, this does not even cover the code to implement it) which is lines 410-479.

However, there is far more beyond that to do for each individual extension before they would be functional. Each could/likely will have different options to select, different settings to configure and other considerations. I will at some point need to research them 1 at a time and after learning how each works implement them one at a time with vigorous testing to ensure they work.

The short of it is, (not having tested it myself) if you use this script to get started its possible to manually install/configure any extension(s) you like. The same challenges apply (as they would for me); knowing how to install and configure them, having the infrastructure to use them and testing and ensuring it works correctly. I do plan on adding what I can to this script in the future, but it will be many months from now and will take considerable time/effort to implement correctly.

**Comment by aekash** [comment]
I managed to install and test both the 2FA extensions  manually after going through your code  to work out what was required 

Thanks :) 👍

**Comment by Zer0CoolX** [comment]
I have split your last post to its own issue "[Help] General Questions", please carry on there as we are no longer on the same topic. Thanks
