### ISSUE TITLE
Development Tools are not being installed with script

### ISSUE THREAD

**Issue by josephreynolds1** [Zer0CoolX/guacamole-install-rhel#34]
Development Tools yum group is not being installed which is causing guacd to fail to compile.

Script proceeds to the point where all of the services are restarted and then bombs out because guacd service is missing.

**Comment by Zer0CoolX** [comment]
Sorry I just noticed this. Please fill out the [Bug] report template under issues and answer as much of it as you can. Please read [How to Report Issues](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/How-to-Report-Issues-(Bugs,-Feature-Request-and-Help)) for guidance on how to best ask for help. Its very hard to help someone resolve an issue with only 2 sentences of information.

Development Tools is a group of packages, and not listed itself as a required dependency by Apache. Everything required to compile Guacamole is included in the script. If you are running into an issue, the information requested in the [Bug] issue template will help me help you.

I am closing this issue, please fill out an issue using the proper template, filled out and I will do my best to help.
