### ISSUE TITLE
[BUG] ./guac-install.sh: line 1093: cd: server: No such file or directory

### ISSUE THREAD

**Issue by TheBarzFR** [Zer0CoolX/guacamole-install-rhel#36]
**Confirmation of Process**
1. You have read the [How to report issues](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/How-to-Report-Issues-(Bugs,-Feature-Request-and-Help)) wiki page? Y
2. You have read the wiki and followed its guidelines, especially the [Installation Assumptions](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/Installation-Assumptions) page? Y
3. You have checked the wiki and existing issues for the same problem? Y
4. You are sure this issue is not specific to you personally and would affect others under similar circumstances? Y

**Describe the bug**
./guac-install.sh: line 1093: cd: server: No such file or directory

**Comment by Zer0CoolX** [comment]
To best help you I need more information than a sentence fragment.

What steps did you take to get the issue?

Whats the script log say?

What OS and version are you trying on? Is it minimal, does it have a DE, etc.?

What selections did you make when running the script? What extension? What Nginx choices? etc.

Did you try running the script again, do you get the same error?

That error basically says that on line 1093 of the script (which is a simple command `cd server`) it could not find the `server` directory. I need some information from you to help determine why. Reply with all the information you can provide and hopefully I can provide you some assistance.

**Comment by Zer0CoolX** [comment]
Closed due to inactivity. Should you still need help, resubmit an issue filling out the whole template and fully explain the problem.
