### ISSUE TITLE
Running the Script Unattended/Silent

### ISSUE THREAD

**Issue by Zer0CoolX** [Zer0CoolX/guacamole-install-rhel#4]
Currently the script has some old code for running in a silent or unattended fashion. I have largely neglected this part of the script. The challenge for me will be to not only add all the "new" options to this part of the script but to check and verify that existing options are accurate.

Once this is updated, it will need to be tested to ensure the results are similar to the interactive method of running the script.

I have a feeling this will take a lot of time and effort, so I could use help in accomplishing it. I am of the presumption that this would be a desirable feature of the script for many people.

Thanks

**Comment by Zer0CoolX** [comment]
With the upcoming new menu implementation and additional features adding to the complexity of the script and so far no progress with updating the unattended/silent ability of the script I am deciding to put this on the back burner. For the time being I am going to completely remove the existing unattended/silent code from the script as its not longer relevant anyhow.

I do not plan on adding the unattended/silent code/feature back into the script for the foreseeable future as I feel the ability is not of paramount importance and the script has moved more into reliance on user input. If I do ever add the unattended/silent feature back, it will only be after every other conceivable improvement, tweak, cleanup, etc. has taken place.

If you feel this is of greater importance please voice the opinion as a feature request. Thanks

**Comment by MarkProminic** [comment]
For those that want to Automate this, I recommend using the Expect Module in Ansible to deploy to VMs:


- name: Install Guacamole
  expect:
    echo: yes
    chdir: "/tmp"
    command: "./guac-install.sh"
    timeout: "900"
    responses:
      (.*)Pick the desired source to install from(.*): "git"
      (.*)Enter the Guacamole DB name(.*): ""
      (.*)Enter the Guacamole DB username(.*): ""
      (.*)Enter the Java KeyStore key-size to use(.*): ""
      (.*)Enter the root password for MariaDB(.*): "GuacDB"
      (.*)Enter the Guacamole DB password(.*): "GuacDB"
      (.*)Enter the Guacamole Java KeyStore password(.*): "GuacDB"
      (.*)Enter the number of the desired SSL(.*): 1
      (.*)Enter a valid e-mail for le(.*): mark.gilbert@m4kr.net
      (.*)Enter the Let's Encrypt key-size to use(.*): ""
      (.*)Use OCSP Stapling(.*): ""
      (.*)Enter the LAN IP of this(.*): "192.168.2.140"
      (.*)Enter a valid hostname or public domain(.*): "html5.dc-01.m4kr.net"
      (.*)Enter the URI path(.*): ""
      (.*)Use only(.*): ""
      (.*)Use Content-Security-Policy(.*): ""
      (.*)Would you like to install any standard (.*): ""
      (.*)Would you like to install a custom Guacamole e(.*): ""
      (.*)Enter the number of the category to review(.*): "7"
    register: expect_example_result
    failed_when: "expect_example_result.rc != 0 and 'Success' not in expect_example_result.stdout"
