### ISSUE TITLE
[HELP] How to update?

### ISSUE THREAD

**Issue by c1xx** [Zer0CoolX/guacamole-install-rhel#43]
**Confirmation of Process**
1. You have read the [How to report issues](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/How-to-Report-Issues-(Bugs,-Feature-Request-and-Help)) wiki page? Y
2. Have you read the [wiki](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki), checking all pages for information that may help you? Y
3. Have you read other requests to ensure this question has not already been asked and/or resolved? Y
4. You understand that this script comes without warranty and is provided as is without any expectation of help from myself or others? Y
5. You understand that submitting a help request does not guarantee a response or solution to your issue? Y

**Environment (please complete the following information):**

 - OS: CentOS 7.6
 - OS Details: Minimal install and used your installation script for Guacamole
 - Browser: Brave / FireFox (latest versions)

**Guacamole Options Selected**

 - Extensions: No Extensions
 - Nginx: Just used your install script
 - LetsEncrypt/Self-signed cert? LetsEncrypt
 - Circumstantial Settings: -

**Logs & Error Messages (be sure not to include sensitive/personal information!)**
No errors

**Screenshots (be sure not to include sensitive/personal information!)**
No Screenshots needed

**Describe the Issue**
I just want to know how I can update my Guacamole from version 1.0.0 to 1.1.0 generally? As mentioned I used your guacamole installations script.

**Is the Problem Reproducible or Random?**
It's not a Problem, just a request.

**Comment by Zer0CoolX** [comment]
This script is only for clean installs as per 1) of my [To Do pages "Things I have decided against doing"](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/To-Do:-Planned-and-Desired-Features#things-i-have-decided-against-doing-in-this-script).

I have yet to find any clear information on the proper procedures to do an in place upgrade from one version to the next. Additionally 1.0.0 is the current stable version. 1.1.0 is the current dev version. Its possible there may not be a direct upgrade path (as there was not really for 0.9.14 to 1.0.0).

I suggest you check the Apache Guacamole site and or their mail list to ask about upgrades.

**Comment by berndhose** [comment]
I have created an upgrade script that seems to work for guacamole installed with your install script. Although this is not related to the clean installation, it might be helpful for in-place upgrades. I have re-used some of your code, and code from another repo here at GIT (https://github.com/MysticRyuujin/guac-install). I have not refined nor tested it extensively with different installation, but it may serve as a starting point. Take a look.
[guac-upgrade.zip](https://github.com/Zer0CoolX/guacamole-install-rhel/files/3065885/guac-upgrade.zip)
