### ISSUE TITLE
[FEATURE] Update procedure

### ISSUE THREAD

**Issue by berndhose** [Zer0CoolX/guacamole-install-rhel#45]
I have created an upgrade script that seems to work for guacamole installed with your install script. Although this is not related to the clean installation, it might be helpful for in-place upgrades. I have re-used some of your code, and code from another repo here at GIT (https://github.com/MysticRyuujin/guac-install). I have not refined nor tested it extensively with different installation, but it may serve as a starting point. Take a look.
[guac-upgrade.zip](https://github.com/Zer0CoolX/guacamole-install-rhel/files/3065961/guac-upgrade.zip)

**Comment by Zer0CoolX** [comment]
Hello, I appreciate the effort and will look it over. As of now, I only intend for this script to be for installs. If it is something you want to maintain it may be best to start your own repo for it. I still have a lot of work ahead of me on this script and dont see me being able to maintain an upgrade script as well in the foreseeable future. Thanks
