### ISSUE TITLE
[REQ] Fail2Ban install and configuration

### ISSUE THREAD

**Issue by nivelo** [Zer0CoolX/guacamole-install-rhel#53]
Hello,

Would it be possible for you to add the instillation and configuration of fail2ban to the script?  as well as adding authentication logging etc.

thanks!

**Comment by nivelo** [comment]
p.s. HACK THE PLANET!!!!!!!!!!!!!!!!!!!

**Comment by Zer0CoolX** [comment]
I have heard of fail2ban but have no experience with it. Can you recommend any good resources for learning more about it and deploying it? If you have any info specifically about deploying it along side Guac, Nginx, Tomcat, etc. that would be even more helpful.

I cant promise I will include it, but I will heavily consider it. If I do add it, it will not be for some time. I am currently trying to work out bugs/clean code/test and am in a feature freeze state. Once I am happy with the script as is, I then plan to start implementing additional official Guacamole extensions like TOTP, DUO, etc. This will require lots of time as I will have to read up on documentation, work out coding it and then work out ways to test it to ensure it does not break anything and works properly.

As for authentication logging, it depends on how you mean. If you mean logging into the Guacamole client/web page, as far as I know these attempts are already logged (I have seen them under `/var/log/messages`). I just checked and can verify this at least for non-LDAP auth.

Try:
`tail -f /var/log/messages`

Open the guac login page and login, you will get a line, something like:
`date/time server host name: time [http-bio-8080-exec-4] INFO o.a.g.r.auth.AuthenticationService - User "user_name" successfully authenticated from x.x.x.x (IP)`
or
`date/time server host name: time [http-bio-8080-exec-4] WARN o.a.g.r.auth.AuthenticationService - Authentication attempt from x.x.x.x for user "user_name" failed`

User activity is logged right within the Guacamole web client, under Active Sessions and History tabs in settings. I presume this was not what you refer to however.

There is currently a post on the Apache Guacamole mailing list about [redirecting logs](http://apache-guacamole-general-user-mailing-list.2363388.n4.nabble.com/Redirect-Guacamole-log-to-another-file-td5413.html) if you want to parse out just the authentication messages to your own log.

I dont see me taking the steps to modify the default logging behavior. First, I am not sure it is widely beneficial to the majority of users and it would also render any information/documentation regarding the default behavior incorrect which could confuse many people trying to review logs themselves.

If I have misunderstood what you meant by logging please further explain, I am happy to hear any suggestions/input from interested users. Thanks for your input so far, interested to hear/learn more about fail2ban, if you are willing and able to provide some resources.

**Comment by nivelo** [comment]
Hi Zer0, 
By far the best way to learn about fail2ban is through the Wiki;
https://www.fail2ban.org/wiki/index.php/MANUAL_0_8

I don't have any specific information about deploying it specifically alongside Guac, Nginx, Tomcat, etc. However I am quite willing to figure out the proper way to do it and create a script to automate the process! I will post my findings and update this thread once I am finished.

thanks!

**Comment by Zer0CoolX** [comment]
I will start poking through the wiki as time permits. I did some research today and was unable to figure out how to connect fail2ban to the logs for Guacamole. Everything online said to point to catalina.out but that seems to be very dated. Guacamole is using syslog now for logging.

Any info you can find, feel free to pass along here. Even if you dont script something and instead just compile notes/resources (like links to guides) and pass it along it could be immensely helpful. I want to make sure if I add it I understand how it works and integrates with the rest of the software so it works properly and helps increase security instead of being a problem for others.

I am guessing it wont be super simple as fail2ban would need to parse the guacamole specific authentication messages from syslog, but it seems to support regex like abilities to get to the info needed. To get started, its just a matter of figuring out how to properly get it to watch Guacs auth logs.

Thanks

**Comment by nivelo** [comment]
Hi,
I have had a look through the best way to set this up and have gotten everything working. The plan is to find a way to kill the active firewall session state because otherwise, if they don't refresh the webpage they can continue to attempt to brute force passwords. 

Once I have done this I will start writing a script to automate the setup process, I plan to write a short guide soon that will allow others to set it up in the mean time.

I will update this feed once I have done that!

thanks!

**Comment by Zer0CoolX** [comment]
Sounds great, look forward to hearing about your progress!

**Comment by Zer0CoolX** [comment]
I am going to close this issue for the time being. Should you make progress and want to share it, either open a new issue or post back in this issue and I can re-open it I presume.

**Comment by dxdemetriou** [comment]
I have used these:

/etc/fail2ban/jail.{conf,local}
```
 [guacamole]
 enabled = true
 port     = http,https,8443
 logpath  = /var/log/messages
```

/etc/fail2ban/filter.d/guacamole.conf
Replaced:
```
 failregex = ^.*\nWARNING: Authentication attempt from <HOST> for user "[^"]*" failed\.$
```
With:
```
 failregex = \bAuthentication attempt from \[<HOST>(?:,.*)?\] for user ".*" failed\.
```

References:
http://mail-archives.apache.org/mod_mbox/guacamole-user/202003.mbox/%3C740954475-23510@quantiss.com%3E
https://www.wilbursecurity.com/2016/08/fail2ban_guacamole/
https://www.cb-net.co.uk/linux/debian-8-6-proxy-guacamole-via-nginx-using-https-and-fail2ban/
https://github.com/fail2ban/fail2ban/issues/1574
