### ISSUE TITLE
script hangs at Creating Required Directories...

### ISSUE THREAD

**Issue by elekgeek** [Zer0CoolX/guacamole-install-rhel#58]
running the script second time causes failure at "Creating Required Directories...", what I did is as follows:

line 1161    mkdir -v /etc/guacamole --> mkdir -vp /etc/guacamole
line 1164    mkdir -v /usr/share/tomcat/.guacamole/ --> mkdir -vp /usr/share/tomcat/.guacamole/

**Comment by Zer0CoolX** [comment]
You have not provided any information about the scenario. Its unclear if you are asking for help or providing feedback.

You mention running the script a second time. The script is meant to be run on a clean install without any remnants of the script present.

If you need further help please fill out the template including the error message, what options you selected, OS/version, etc. I am going to close this issue.
