### ISSUE TITLE
[Help] General Questions

### ISSUE THREAD

**Issue by Zer0CoolX** [Zer0CoolX/guacamole-install-rhel#61]
I managed to install and test both the 2FA extensions  manually after going through your code  to work out what was required 

Thanks :) 👍 

If you use the LetsEncrypt option for SSL Certificate do you have a cron job to check for / and renew the certificate or is this something you plan to implement  in future ?

If you do check for / and renew how often do you check  for when the LetsEncrypt cert is due to expire and when does the renew occur ?

I think I've learnt a lot of Linux today just by analysing your code and testing out things.....

_Originally posted by @aekash in https://github.com/Zer0CoolX/guacamole-install-rhel/issues/32#issuecomment-501870819_

**Comment by Zer0CoolX** [comment]
The SSL cert will auto renew every 3 months automatically, the script takes care of this by using the provided service and timer from the certbot package installed from the official repos. This can be seen on lines 1767-1773 and confirmed via the logfile generated by the script as per the output of script line 1771.

For further info on the "how", I would recommend reading the service and timer files. Honestly, I just now it works and thats good enough for me. Its part of the reason I use certbot from the CentOS/RHEL repos and not downloaded/install from other sources (which I used to do instead long ago in this script).

Glad to hear you got 2FA setup, if you would mind sharing the steps you took I would be interested to know. May help me down the line with implementing it as part of the script.

**Comment by aekash** [comment]
Here you  go.....

**1. TOTP two-factor authentication - https://guacamole.apache.org/doc/gug/totp-auth.html**

1.1  I used wget  to download "guacamole-auth-totp-1.0.0.tar.gz" from https://guacamole.apache.org/releases/1.0.0/

1.2  Unpacked the file  
      tar xvzf guacamole-auth-totp-1.0.0.tar.gz

1.3 Copied the extracted file to  "/var/lib/guacamole/extensions/"
      sudo cp /home/administrator/guacamole-auth-totp-1.0.0/guacamole-auth-totp-1.0.0.jar 
      /var/lib/guacamole/extensions/

1.4.  Applied SELINUX settings (taken your from script)
      sudo semanage fcontext -a -t tomcat_exec_t "/var/lib/guacamole/extensions/guacamole-auth-totp- 
      1.0.0.jar"
      sudo restorecon -v "/var/lib/guacamole/extensions/guacamole-auth-totp-1.0.0.jar"

1.5   Added the following guacamole properties  (optional)
     /guacamole/guacamole.properties
     
     ## TOTP settings
     #Name of the code in the app
      totp-issuer: 
    #Number of numbers
      totep digits:   6
   #New code every xx seconds
      totp-period: 30
   # Hash algorithm - "sha1", "sha256" or "sha512"
       totp-mode: sha1

1.6. Restarted tomcat service
       systemctl restart tomcat

**2. Duo two-factor authentication - https://guacamole.apache.org/doc/gug/duo-auth.html**

2. 1 I used wget  to download "guacamole-auth-duo-1.0.0.tar.gz" from 
       https://guacamole.apache.org/releases/1.0.0/

2.2  Unpacked the file  
       tar xvzf guacamole-auth-duo-1.0.0.tar.gz

2.3  Copied the extracted file to  "/var/lib/guacamole/extensions/"
       cp /home/administrator/guacamole-auth-duo-1.0.0/guacamole-auth-duo-1.0.0.jar 
       /var/lib/guacamole/extensions/

2.4  Installed PWGEN  and  created a new key
       yum install pwgen
       pwgen 40 1   (took note of the key generated)

2.5.  On Duo.com added the application "Web SDK"

2.6   Added the following guacamole properties  ( not optional / is required)
     /guacamole/guacamole.properties

     ## Duo Security
     duo-integration-key: [XXXXXXXXXXXXXXXXXXXXX] <------ obtained from "Web SDK" registration 
    duo-secret-key: ]xxxxxxxxxxxxxxxxxxxxxxxxxxxxx] <------ obtained from "Web SDK" registration 
    duo-api-hostname: api-[xxxxxxxxx].duosecurity.com <------ obtained from "Web SDK" registration 
    duo-application-key:  [ xxxxx] <----- KEY generated in step 2.4

**Comment by Zer0CoolX** [comment]
Excellent feedback! Thank you.

I will leave this issue open for another few days should you have any further questions. If you do not or have not posted back in that time I will close the issue for now.
