### ISSUE TITLE
[Help] Changing Default Port Used by Client

### ISSUE THREAD

**Issue by marcelopmachado** [Zer0CoolX/guacamole-install-rhel#62]
Good afternoon, do not speak English so I'm using google translator, sorry if I get a little confused my question so
I installed Guacamole using the script, it worked fine, however after the installation and make it work internally in my network, I need to redirect the external ports to access it, but how it uses the default port 80, I can not redirect because we use this port as default for another page, would like to change the guacamole navigation port to another example: 8095

I'm using CentOS 7 and Git's guacamole

**Comment by Zer0CoolX** [comment]
If I understand correctly, you want to change the port the Guacamole client (web page) connects on?

Currently it connects over 80/443 depending on your setup. Using a self-signed cert or Let's Encrypt will force HTTPS, thus 443.

I will be honest, I have never tried an alternate port and can only provide you some information and recommendations for things to research to try and work it out.

As far as I am aware you may only need to adjust the entries in:
- /etc/nginx/conf.d/guacamole.conf
- /etc/nginx/conf.d/guacamole_ssl.conf

Changing the "listen" lines to the desired ports. In addition, you will likely need to change configurations for the HTTP/HTTPS services in CentOS to assign them the desired ports. You may have further tweaks to make like opening the proper ports in firewalld.

I am afraid I wont be able to help more than that as its not a supported configuration at this time. Good luck
