### ISSUE TITLE
[BUG]  RDP client not working after install

### ISSUE THREAD

**Issue by laramy2020** [Zer0CoolX/guacamole-install-rhel#63]
**Confirmation of Process**
1. You have read the [How to report issues](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/How-to-Report-Issues-(Bugs,-Feature-Request-and-Help)) wiki page? Y
2. You have read the wiki and followed its guidelines? Y
3. You have checked the wiki and existing issues for the same problem? Y
4. You are sure this issue is not specific to you personally and would affect others under similar circumstances? Y and N

**Describe the bug**
RDP not working after build compeltion. I have the stock freerdp-libs and freerdp package installed. I normaly use mikedep333's freerdp copr repo as it has the newer freerdp2, but i reverted back to see if that was the issue. The connection fails and tried to reconnect. Looking at logs it says rdp is not installed.

**Error Message(s) and Logs (be sure not to include sensitive/personal information!)**
If an error occurred include the exact message from the display/log.
```
journalctl -xe -u guacd
Jun 19 11:33:49  guacd[29820]: Support for protocol "rdp" is not installed
Jun 19 11:33:49 1 guacd[29572]: guacd[29820]: WARNING:        Support for protocol "rdp" is not installed
Jun 19 11:33:49  guacd[29572]: Connection "$93ba712e-b883-4f83-a4fc-c70d5264fcc5" removed.
Jun 19 11:33:49  guacd[29572]: guacd[29572]: INFO:        Connection "$93ba712e-b883-4f83-a4fc-c70d5264fcc5" removed.
```
in the webpage

> 
> Connection Error
> 
> The connection has been closed because the server is taking too long to respond. This is usually caused by network problems, such as a spotty wireless signal, or slow network speeds. Please check your network connection and try again or contact your system administrator.

**To Reproduce**
1. Go to 'home'
2. Click on 'any rdp session'
3. rdp session fails

**NOTE**
The more information you provide the easier it is to help!

**Screenshots (be sure not to include sensitive/personal information!)**

**Environment (please complete the following information):**
 - OS: centos 7.6.1810
 - OS Details: bare metal install on laptop, Gnome desktop
 - Browser: broswer used on localhost (no external use planed) Firefox 60.7.0esr

**Guacamole Options Selected (This is very important, without knowing selections made its very hard to help.)**
 - Extensions: none
 - Nginx: not using (going to localhost:8080/guacamole
 - LetsEncrypt/Self-signed cert?: none
 - Circumstantial Settings: n/a
 - Other:n/a

**Have You Found a Solution to the Issue?**
Either by manually doing something before/after the script has run or by editing the script prior to running.
if using stock freerdp from centos, installing libguac-client-rdp fixes it, but sound does not work.

**Comment by Zer0CoolX** [comment]
Hello. Sorry your having trouble. I will need to ask you some stuff to try and help you resolve things.

1. Did you get an error message while the script was running or did it complete? If you got an error please share it.
2. Please confirm the build date of the script you used (variable towards the top of the script)
3. Was the script run on a clean install of CentOS or did you install other complex software/services/roles on CentOS prior? IE anything that would have installed/configured: nginx, mariadb, or any other software installed/configured by the script?
4. Have you checked the log file generated by the script for any errors? If you found anything in the log please let me know what it says. Specifically check the part during compiling Guacamole server...there is  a part that displays what capabilities are being compiled into it and which are not, RDP should be listed and state something to the effect of supported/install.
5. Have you tried doing a clean CentOS install and trying the script again?
6. Are you able to RDP to the client machine directly (aka from Windows RDP client or another, known working RDP client)?

If I had to guess based on your error message, Guac didnt compile with support for rdp, so adding the packages in any form wont change that.

I would recommend looking into the above numbered list of things to check, let me know the answers and see what the best resolution will be.

**Comment by laramy2020** [comment]
1: i did not receive any errors
2: ```SCRIPT_BUILD="2019_6_6" # Scripts Date for last modified as "yyyy_mm_dd"```
3:only the copr repo of freerdp and i think that is the issue, will link at end
4:i did not check that log and here is the error in ./configure
```configure: WARNING:
  --------------------------------------------
   Unable to find libfreerdp-core / libfreerdp
   RDP will be disabled.
  --------------------------------------------
```
so rdp was set to no
5:no this is a work laptop
6:yes

looks like freerdp2 (which is still not "offical" yet after years, it is even availabel in ubuntu 18.04) is not supported in 1.0.0 i have mvn failures with the git version of the script. i will try and redo the script again on stable with the stock rdp
I will remove /etc/guacamole & /usr/share//guacamole
remove my mysql databases and users
and re-run the script.
Other than that. it looks like it was user error so far. 
https://issues.apache.org/jira/browse/GUACAMOLE-249

**Comment by laramy2020** [comment]
so the newer freerdp2 is not supported yet by guac.
I do have other issues, but should i will check the issue tracker first, one has to do with drive passthrough and sound passthrough

**Comment by laramy2020** [comment]
all my isues but sound is fixed.
i am not seeing any errors for sound. so this might be some self debug.

**Comment by Zer0CoolX** [comment]
Glad to hear you have worked some of it out. As for audio, I can confirm it can work as I have it running on some machines over RDP. I would check the machines and ensure they have audio drivers installed and any configuration on those machines required for audio/audio over RDP are set (like the Windows Audio service being set to run).

For a connection, ensure "disable audio" is not checked in device redirection. If your browser supports muting audio for tabs, make sure its not blocking audio from Guac. You may try an alternate browser if you have not already to see if its possibly browser related.

Hopefully this helps. I will leave the issue open for a couple days in case you need further help.

**Comment by laramy2020** [comment]
Thanks for the help. i will keep looking into the audio issues. I know it works when i run the freerdp command in cli. so i will check chrome to see if that is the one making the issue.
