### ISSUE TITLE
[REQ] Add option to generate new script file across multiple servers

### ISSUE THREAD

**Issue by sloanja** [Zer0CoolX/guacamole-install-rhel#67]
**Confirmation of Process**
1. You have read the [How to report issues](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/How-to-Report-Issues-(Bugs,-Feature-Request-and-Help)) wiki page? Y
2. You have read the wiki, especially the To Do: [Planned and Desired Features](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/To-Do:-Planned-and-Desired-Features) page? Y
3. You have read other requests to ensure this feature has not already been requested? Y

**In a sentence or 2, describe briefly what the idea is**
Add an option at the end for "Accept and Build Install Script".  This would be for a code review of the changes to be made as well as to copy the script to be ran on multiple servers.  The other option would be to allow the guac-install.sh script to take input variables or answers in an XML file.

**Is your feature request something that would help the majority of people using this script in typical environments or use cases?
Y - for larger deployments of Guacamole, or need to repeatedly install the same environment.

**Is your feature request related to a problem?**
N

**Describe the idea/feature you'd like**

**Any links, documentation or resource that would help implement this feature**
The more resources you provide the better I can address if adding the feature is possible and how I can best do so.

**Additional context**

**Comment by Zer0CoolX** [comment]
> Add an option at the end for "Accept and Build Install Script". This would be for a code review of the changes to be made...

Unless I misunderstand, this is essentially what the summary menus provide. Not only do they provide means to review all of the user set parameters, they provide the option to change them before any changes are made to the system. Combined with the option to "Cancel and Start Over" or "Cancel and Exit", its possible to prevent the script from making any changes to a system without the user consenting.

The script itself is "open source" so to speak, in that anyone can review the code and determine if they agree with all of the actions the script takes. I have tried to make it as easy to follow as possible with comments where it makes sense. In addition, I have spent a lot of effort on writing and maintaining the wiki and readme page here to provide in depth information on how everything works.

> ...as well as to copy the script to be ran on multiple servers. The other option would be to allow the guac-install.sh script to take input variables or answers in an XML file.

I follow this and certainly see the benefits. Ironically enough, the very early versions of this script did provide cli arguments for options, which could hypothetically have had answers passed to it by an answer file.

As the script become much more complex, I was unable to keep up with supporting a cli side to the script. I decided at the time to remove the cli arguments and help and focus on the guided install provided by the script.

The intention of this script, leading up until now, is for a single install on a single system to run as the sole Guacamole server in a given environment from a single machine (physical or VM) with no other roles other than acting as a Guacamole server.

While I believe Guacamole can support things like load balancing in multi-Guacamole environments, it would almost certainly increase complexity and is well beyond my understanding of both Guacamole and Linux.

So the value of a cli based mechanism is a bit diminished when you consider its intended use, one time on a single server. Then consider how many parameters are actually required (most are not optional) and manual cli starts to become less feasible (is someone really going to manually type out 50, 100 or more switches in a cli command?).

The only way it can viably be used is with an answer file at that stage. This adds further complexity to the script as one would now have to parse the answer file, decide on proper syntax's within the file, document the proper way to create/use an answer file, etc. Keep in mind the script itself is still only intended to be used and config a single server. So all that effort to save a minute or 2 vs entering the information via the guided prompts which offer additional benefits like being able to review answers and make changes.

Dont get me wrong, I appreciate the input and I agree that down the road, adding cli and/or answer file capabilities may be a value add. However, I think that added value would only come if I end up putting a lot of additional effort into the script to support multi-server setups or some other feature that would end up saving a significant amount of time vs using the menus.

For now I am going to leave this open so you may comment. If you have nothing else to add after a few days I will close this request and take it under consideration.

Thanks

**Comment by sloanja** [comment]
I often have to repeatedly test setups and reinstall often as part of a lab scenario.  While it may not save time that much from your perspective, doing this repeatedly to prove reliability of the service Guacamole provides eats up a chunk of time especially when it's a similiar setup across multiple systems. 

Thank you for your time.

**Comment by Zer0CoolX** [comment]
> I often have to repeatedly test setups and reinstall often as part of a lab scenario.

That is an excellent point. I will do some research and see how much effort it would take to implement something like this. If its not as complex as I think it may be I will see if I can at least start some work towards it.

Thanks!
