### ISSUE TITLE
[REQ] Add required firewall ports for system

### ISSUE THREAD

**Issue by sloanja** [Zer0CoolX/guacamole-install-rhel#68]
**Confirmation of Process**
1. You have read the [How to report issues](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/How-to-Report-Issues-(Bugs,-Feature-Request-and-Help)) wiki page? Y
2. You have read the wiki, especially the To Do: [Planned and Desired Features](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/To-Do:-Planned-and-Desired-Features) page? Y
3. You have read other requests to ensure this feature has not already been requested? Y

**In a sentence or 2, describe briefly what the idea is**
Add a detection if the default firewalld service is enabled, and if so, add required persistent firewall ports to be allowed to firewalld.  Optionally, add question to disable firewalld service with strong recommendation to not do this.

**Is your feature request something that would help the majority of people using this script in typical environments or use cases?
Y - for larger deployments of Guacamole, or need to repeatedly install the same environment.

**Comment by Zer0CoolX** [comment]
Could you clarify your request for me, I am not sure I follow exactly what you are proposing.

What do you mean when you say:

> add required persistent firewall ports to be allowed to firewalld

The script in its current form opens ports by service for `HTTP` and `HTTPS`, so even if they are not the default ports, as long as the `HTTP` and `HTTPS` services know the ports, the script should be able to open the proper ports in `firewalld`. However, `tomcat` uses `8080` and `8443` by default. I have not looked into it but changing these ports would take much more than just adjusting firewall rules.

For some background. There is currently a mechanism in the script that does check if `firewalld` is installed, and if so to ensure its enabled and running. However I do see now that I have no logic in place to handle if its not installed.

RHEL/CentOS include `firewalld` installed by default and it is enabled and running by default. It would have to removed intentionally and/or disabled intentionally prior to running the script for it to not be installed and running.

Is there any benefit to uninstalling `firewalld` or disabling it that does not sacrifice security?

If what you are proposing is along the lines of providing an option to pick the desired firewall to use (or none) I would need suggestions for alternative firewalls to use.

Any additional info about your request/idea would help me better understand what you aim to do and how.

**Comment by sloanja** [comment]
I installed it this morning and I couldn't access it until after I stopped the firewalld service. It's possible the firewalld wasn't restarted to make the changes live.  The script could easily restart the firewalld service.

**Comment by Zer0CoolX** [comment]
> It's possible the firewalld wasn't restarted to make the changes live. The script could easily restart the firewalld service.

The script does reload `firewalld` as per line 1744-1746 of the script (master branch) using the command: `firewall-cmd --reload`.

That should be enough for it to take on the firewall rules set by the script.

If you did not receive any kind of error message, it could have been a one time quirk. I have never had it happen but I could potentially add `firewalld` to the block towards the end of the script in which I restart many other services (lines 1817-1828 of master branch) just to be sure.

Thanks
