### ISSUE TITLE
[BUG] the script doesn't install wget when it's missing.

### ISSUE THREAD

**Issue by chrnin** [Zer0CoolX/guacamole-install-rhel#70]
Hi,

the script crashed here because wget was missing on my centos 7 install.
That would be pretty easy to check and install it when it's missing.

Have a good day :)

Christophe.

**Comment by Zer0CoolX** [comment]
Can you please share the error message the installer gave?

The script installs wget, and I have never seen this issue in my testing. Any additional info you can give may be helpful. What source did you use for install (stable/git), what options did you select from the menus, etc.

Line 1029 of the script installs wget along with many other packages. Prior to this command running,at a glance, I dont see wget being used any place else.

With more details we can figure out what if any action needs to occur to prevent the issue.

Thanks

**Comment by chrnin** [comment]
Hi, sorry I indeed made a poor bug description, I was late and I were a little tired.. 
I'm glad you found the issue ! Line 998 is indeed a good candidate, the issue occurred while trying to install the libjpeg-turbo repo !

**Comment by Zer0CoolX** [comment]
I have already added a fix to the master branch for this issue. `wget` is now installed prior to any instance of it needing to be used. Thanks!

**Comment by plexcloud-lab** [comment]
However if wget is already installed  on the system and you run the script is crashed out on line 998
