### ISSUE TITLE
[BUG] mariadb and timezone

### ISSUE THREAD

**Issue by chrnin** [Zer0CoolX/guacamole-install-rhel#72]
Hi,

During install, I also had issues with mariadb crashing on the service restart because of a timezone issue. I took a look to understand what was going on and I found that on my system, the timezone link wasn't like the script thought it should be... It's a custom centos 7 flavor given by my IT team, so... I think it's probably also a customized error, but it would be nice that the script takes account of user custom situations.

Here, my timezone link is like this:
```
[centos@signfaib-rebondssh ~]$ readlink /etc/localtime 
/usr/share/zoneinfo/Europe/Paris
```

Line 1259, the script does this:
```
	MY_TZ=`readlink /etc/localtime | sed "s/\.\.\/usr\/share\/zoneinfo\///"`
```
In my case, there are no .. before the path, resulting in a wrong my.cnf directive:
`default-time-zone='/usr/share/zoneinfo/Europe/Paris'` instead of `default-time-zone='Europe/Paris'`. Mariadb didn't survived to this and that stopped the installation process.

I think `readlink /etc/localtime |grep -oP '(?<=/usr/share/zoneinfo/).*'` would avoid a lot of issues like this.

Regards,

Christophe.

**Comment by Zer0CoolX** [comment]
Hello, Thanks for reporting this.

Can you confirm the following for me?

If you do the command:
`ls -al /etc/localtime`

Does the result show something like: `/etc/localtime -> /usr/share/zoneinfo/Europe/Paris` ?

Alternatively what does the command `readlink /etc/localtime` output for you?

Does this command return the expected result for you?
`readlink /etc/localtime | sed "s/.*\/usr\/share\/zoneinfo\///"`
of
`Europe/Paris`

My understanding is that `..` is a special kind of name-inode map which is like a hardlink and represents the parent directory. I wonder why you would not have that in your symlink for /etc/localtime. In any case let me know the answers to the above and I will implement a fix.

Thanks

**Comment by chrnin** [comment]
Here are the answers:
```
$ ls -al /etc/localtime
lrwxrwxrwx. 1 root root 32  3 mai   10:36 /etc/localtime -> /usr/share/zoneinfo/Europe/Paris
```
```
$ readlink /etc/localtime
/usr/share/zoneinfo/Europe/Paris
```
```
$ readlink /etc/localtime | sed "s/.*\/usr\/share\/zoneinfo\///"
Europe/Paris
```
This sed command seems to make a good job in each case !
```
[centos@signfaib-rebondssh ~]$ echo '/usr/share/zoneinfo/Europe/Paris'| sed "s/.*\/usr\/share\/zoneinfo\///"
Europe/Paris
[centos@signfaib-rebondssh ~]$ echo '../usr/share/zoneinfo/Europe/Paris'| sed "s/.*\/usr\/share\/zoneinfo\///"
Europe/Paris
```

Symlinks are either relative (to the symlink place) or absolute path, in our case, given the symlink is in /etc, ../ destination is equal to / and the two alternatives (../usr/... or /usr/...) can work.
I have no idea why you have a ../ish symlink and I have a /ish one, I didn't try to modify it because my IT team would probably have issues with that, maybe they set it directly with a ln -s command.

Regards.

**Comment by Zer0CoolX** [comment]
Thanks for the feedback. I have updated the script using the sed line (1259 currently) we have both tested and confirmed working. If you wouldn't mind give the script another shot and see if this resolves the matter for you.

**Comment by chrnin** [comment]
Thanks, I don't have any server to install for the moment, I think I won't test it in the next weeks.. But I'll use your script the next time I install apache guacamole for sure. ;)

**Comment by Zer0CoolX** [comment]
I understand if you cannot, not to push the matter but even if you can give it a shot in a VM using that OS image of yours that would help. I would test it myself but honestly not sure how to reproduce the symlink not having the `..` in front of it as it is on your system.

Either way, Thanks for your tremendous help!

**Comment by MarkProminic** [comment]
I can also confirm that I am having this same issue, with the Updated sed command.  The only way that I have been able to get this to properly install is to remove the section from lines 1253 - 1263. 

The My.cnf looks to be set correctly with the correct value. I use either UTC or America/Chicago and in both situations this is set in the My.cnf correct and MySQL (MariaDB) does start and stop when initiated via server mariadb stop, start, and restart. 


It seems as if there is a timeout.
as the shell script errors out with:  Script failed on line 875 (# Check if background process failed once complete)

![](https://www.m4kr.net/SuperPutty_QPYCudYEQY.png)
