### ISSUE TITLE
[REQ]  Allow using a Windows certificate generated by a Windows CA

### ISSUE THREAD

**Issue by riahc3** [Zer0CoolX/guacamole-install-rhel#73]
**Confirmation of Process**
1. You have read the [How to report issues](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/How-to-Report-Issues-(Bugs,-Feature-Request-and-Help)) wiki page? Y
2. You have read the wiki, especially the To Do: [Planned and Desired Features](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/To-Do:-Planned-and-Desired-Features) page? Y
3. You have read other requests to ensure this feature has not already been requested? Y

**In a sentence or 2, describe briefly what the idea is**
The certificate generated using a Windows CA and use that in Guacamole. Script should import windows ca for trust and import cert for Guacamole.

**Is your feature request related to a problem?**
N

**Describe the idea/feature you'd like**
The certificate generated using a Windows CA and use that in Guacamole. Script should import windows ca for trust and import cert for Guacamole.

**Any links, documentation or resource that would help implement this feature**
https://www.centos.org/forums/viewtopic.php?t=61275
https://www.sslshopper.com/move-or-copy-an-ssl-certificate-from-a-windows-server-to-an-apache-server.html
https://zeropointdevelopment.com/how-to-get-https-working-in-windows-10-localhost-dev-environment/

**Comment by Zer0CoolX** [comment]
Thanks for submitting the request, I will look into it and see if there is a viable way to incorporate this. No ETA, but this is likely a long ways out.

**Comment by riahc3** [comment]
What a shame. Its a showstopper for me. I, and I imagine many other enterprise users, use Windows certificates.

**Comment by Zer0CoolX** [comment]
For what its worth, the script currently has an option for no cert. I put this in for situations like this that call for a cert setup not yet in the script.

So it is for the time being possible to setup any cert manually, which is better then also needing to setup all of Guacamole manually as well.

You are however right, I can see how this may be more important than I previously considered. The only reason I state that it is possibly far off is I have many other features planned, that I have stated I will work on, prior to this.

Thanks

**Comment by Zer0CoolX** [comment]
I have added this under projects | to-do. Thanks
