### ISSUE TITLE
[REQ] Ability to choose MySQL/Maria DB server

### ISSUE THREAD

**Issue by str8edgedave** [Zer0CoolX/guacamole-install-rhel#74]
**Confirmation of Process**
1. You have read the [How to report issues](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/How-to-Report-Issues-(Bugs,-Feature-Request-and-Help)) wiki page? Yes
2. You have read the wiki, especially the To Do: [Planned and Desired Features](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/To-Do:-Planned-and-Desired-Features) page? Yes
3. You have read other requests to ensure this feature has not already been requested? Yes

I would like to see the script as for a MariaDB/MySQL server hostname during the installation.

**Is your feature request related to a problem?**
N

**Describe the idea/feature you'd like**
During the Database setup questions, a choice to install the DB on the local box, or use an existing DB on another server. A simple connection test can be done using the mysql client to ensure that there are sufficient privileges before installation begins.

**Comment by Zer0CoolX** [comment]
Interesting proposition. Could you possibly elaborate on the benefit of using a database on/from another system?

As the script currently works, it uses MariaDB locally and creates a database and user specifically for Guac. This includes pushing schema changes provided by Guac via .sql files. It also applies a fix to the my.cnf file to prevent issues related to timezone.

To make sure I understand, are you proposing doing this (a fresh database setup for Guac) on a remote server or are you suggesting using an existing database on another server for Guac to use?

Also, what would happen if the remote database cannot be reached? I would presume logins would cease working?

I am trying to understand what benefit having a database only used by Guacamole not on the same sever as Guacamole would provide. Would it make managing multiple databases easier or something of that sort?

Any additional info you can provide may be helpful. Thanks
