### ISSUE TITLE
[REQ] Skip nginx reverse proxy configuration

### ISSUE THREAD

**Issue by mbinns** [Zer0CoolX/guacamole-install-rhel#75]
**Confirmation of Process**
1. You have read the [How to report issues](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/How-to-Report-Issues-(Bugs,-Feature-Request-and-Help)) wiki page? Y
2. You have read the wiki, especially the To Do: [Planned and Desired Features](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/To-Do:-Planned-and-Desired-Features) page? Y
3. You have read other requests to ensure this feature has not already been requested? Y

**In a sentence or 2, describe briefly what the idea is**
Allow the option to skip nginx reverse proxy configuration.

**Is your feature request related to a problem?**
N

**Describe the idea/feature you'd like**
Allow the user to skip the reverse proxy configuration for guacamole.

**Any links, documentation or resource that would help implement this feature**
N/a

**Additional context**
User has existing reverse proxy as a separate host in the DMZ.

**Comment by Zer0CoolX** [comment]
I appreciate the request. At this time, however, it does not fit the intentions I have for the script to configure a mostly/wholly self contained, single instance Guacamole server.

I have stated in: https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/To-Do:-Planned-and-Desired-Features#what-this-guacamole-script-is-not, specifically 4:

> I have no plans to use alternatives to the software being used, like an alternative to Nginx.

You may certainly alter the script as needed, either stripping out Nginx from it, replacing Nginx or limiting the changes to Nginx and manually replacing it.

I may reconsider this in the future, but at this time it would require drastic changes to the script to work properly. For example Let's Encrypt requires the server be reachable on port 80 to acquire a cert, which the Nginx portion of the setup facilitates. I would need to implement and test a whole other set of conditions to ensure an alternate reverse proxy running external to the server is setup correctly to prevent Let's Encrypt failing. The scale of the changes and testing that would be required are just outside of the scope of what I intend this project to accomplish.

That does not mean that goal cannot change, it just means I do not see it changing to that extent at this time. My apologies.

Thanks

**Comment by mbinns** [comment]
Okay,
thanks for getting back to me, have a great day!
