### ISSUE TITLE
[BUG] Firewalld related

### ISSUE THREAD

**Issue by gicapp** [Zer0CoolX/guacamole-install-rhel#88]
**Confirmation of Process**
1. You have read the [How to report issues](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/How-to-Report-Issues-(Bugs,-Feature-Request-and-Help)) wiki page? Y
2. You have read the wiki and followed its guidelines including requirements, troubleshooting, etc.? Y

**Details**
OS/Version: CentOS 7.7
Guacamole Source: Stable/Git? Stable
Any other options selected from the script prompts: Just branding.jar

**Describe the bug**
Got an error from installation, looks like script was expecting a running/working firewalld installation.

**Error Message(s) and Logs (be sure not to include sensitive/personal information!)**
If an error occurred include the exact message from the display/log.

%%% ERROR (Script Failed) | Line 1673 | Command: cp /etc/firewalld/zones/public.xml /root/guacamole-1.0.0_30-19-Oct.firewall.bkp | Exit code: 1 %%%

**To Reproduce**

Just try to install without firewalld file at /etc/firewalld/zones/public.xml

**Have You Found a Solution to the Issue?**

Yes, as my CentOS installation was minimal, i did:

As root:
yum install firewalld
touch /etc/firewalld/zones/public.xml

And worked.

**Comment by Zer0CoolX** [comment]
Thanks for reporting this.

You are correct, the expectation is that `firewalld` is installed and running. That is the default configuration for a minimal RHEL/CentOS install however, so I am wondering why you did not have it.

Where you using a custom ISO or image that could have had `firewalld` removed?

It looks like you got things working on your end.

I am considering/planning to revise the checks I perform at the start of the script, I will add checking for `firewalld` to my list of things I should consider checking for. Thanks

**Comment by gicapp** [comment]
Hi,

Was untouched ISO from CentOS mirror, really don't know why firewalld wasnt there/installed already as should. I'll download again to be sure and check CRC as usual.

Thank you for script (great job) and all your time.

**Comment by Zer0CoolX** [comment]
My pleasure. That's very odd about the CentOS install missing `firewalld`. If you find an answer as to why let me know. For now I am going to close this issue.

**Comment by dragonfly4** [comment]
@Zer0CoolX 
Had the same error. Clean CentOs 7.6 image from Digital Ocean is missing firewalld.

Maybe best to include this check in your script?
