### ISSUE TITLE
[HELP]Cannot associate a user with any connections.

### ISSUE THREAD

**Issue by LightMoon** [Zer0CoolX/guacamole-install-rhel#90]
**Confirmation of Process**
1. You have read the [How to report issues](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/How-to-Report-Issues-(Bugs,-Feature-Request-and-Help)) wiki page? Y
2. You read the [wiki](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki), checking all pages for information that may help you? Y
3. You read other requests to ensure this question has not already been asked and/or resolved? Y

**Details**
OS/Version: RHEL 7.6
Guacamole Source: Stable
Any other options selected from the script prompts:

I don't know if this is an issue or designed in this way.

I have problem in creating a user and associate it with the connection I already have.
Good to note, the user creates successfully and I can log in with the user, however, I cannot associate any connection with the newly created user.

**Comment by LightMoon** [comment]
Update; 

I connected to MariaDB via command line and can confirm the users have been created successfully.

`
MariaDB [guac_db]> select user_id, entity_id from guacamole_user;
+---------+-----------+
| user_id | entity_id |
+---------+-----------+
|       1 |         1 |
|       2 |         2 |
|       5 |         6 |
+---------+-----------+
3 rows in set (0.00 sec)
`

**Comment by Zer0CoolX** [comment]
Can you explain the exact issue. What are you trying to do (steps), do you get an error, what do you expect to happen?

Have you checked error logs?

If I am understanding, by associate a user with a connection do you mean:

1. Settings | Users | (your user)
2. Scrolling down to connection under the specific user and expanding the tree of connections out.
3. Ticking all the boxes from the specific connection up the parent items in the tree
4. Clicking the Save button at the bottom of the screen

So for example if you have a group called "Workstations" with a group called "SomeUser" and the connection is called "MachineA" then you need to tick the boxes for all 3 for "MachineA" to be visible and usable by the given user. Ticking just "MachineA" gives them right to it, but they cant see it unless they have permissions to navigate the groups too.

Also, is this issue limited to a single user or are you not able to associate any user with any connection?

You need to explain what is happening and not happening in detail. IE: does it let you check all the boxes and save but the user cant see the connection as an option or does it fail when saving or does the connection display but the user gets an error when trying to connect to it, etc?
