### ISSUE TITLE
[HELP] Windows RDP not mapping keys correctly when using non US keyboard 

### ISSUE THREAD

**Issue by riahc3** [Zer0CoolX/guacamole-install-rhel#94]
Hello

It seems this is a Guacamole issue....

Im using a spanish keyboard and RDPing into a english Windows. For some, odd reason, it is not correctly mapping the keys. In Windows, I have made sure that the spanish keyboard is selected.

https://www.cb-net.co.uk/linux/guacamole-rdp-en-gb-keyboard-mapping/
https://issues.apache.org/jira/browse/GUACAMOLE-233

From a quick search, it seems that if the correct key mapping is not added, it is impossible to later use it. Im not entirely sure of the fix but could you fill us in, please? It obviously destroys workflow.

Thank you

**Comment by Zer0CoolX** [comment]
Try this:

1. In Guacamole goto settings | connections
2. Select the desired connection to apply key mapping to
3. Under Basic settings, "keyboard layout" select the desired layout.
4. Scroll all the way down and hit the save button.

This should set the keymap for that connection. All included default keymaps can be found in `/usr/local/src/guacamole/1.0.0./server/src/protocols/rdp/keympas/`.

If that does not work, this seems like a guacamole specific bug, not a bug with the installation script. I would recommend looking for help either from the official guacamole forums, submitting a bug to them directly or seeking help from other general Guacamole sources.

I dont have the means to test this nor the ability to fix it if its a bug in Guacamole itself.

**Comment by Zer0CoolX** [comment]
Also, to confirm the map being used by a connection do the following:

1. ssh/terminal to the Guacamole server.
2. In a browser login to Guacamole.
3. In terminal run the following command:

```sudo tail -f /var/log/messsages```

4. In the browser, start an RDP connection to an existing connection.
5. In the terminal, output from the `tail` command should show a line or 2 regarding the keyboard map used, for example:

```...
Jan 23 09:12:58 t-centos-7 guacd: guacd[26921]: INFO:#011Loading keymap "base"
Jan 23 09:12:58 t-centos-7 guacd: guacd[26921]: INFO:#011Loading keymap "en-us-qwerty"
Jan 23 09:12:58 t-centos-7 guacd[26921]: Loading keymap "base"
Jan 23 09:12:58 t-centos-7 guacd[26921]: Loading keymap "en-us-qwerty"
Jan 23 09:12:59 t-centos-7 guacd[26921]: guacdr connected.
Jan 23 09:12:59 t-centos-7 guacd[26921]: guacsnd connected.
...
```
The map should list that selected from the settings I mentioned earlier.

Again I recommend reaching out or opening a bug with Guacamole directly should the problem persist.
